#!/usr/bin/env bash
# Yamada Hayao
# Twitter: @Hayao0819
# Email  : hayao@fascode.net
#
# (c) 2019-2020 Fascode Network.
#

set -e

alterlive=false
force=false
checklive=false

_help() {
    echo "usage ${0} [options]"
    echo
    echo " General options:"
    echo "    -f | --force        Force overwriting."
    echo "    -h | --help         This help message and exit."
    echo "    -l | --live         Opens the page only in a live environment."
    echo "                        Whether it is a live environment or not is determined"
    echo "                        by the presence or absence of the installer."
    echo
    echo "         --alterlive    Remove the file for live session"
}

# Argument analysis and processing
options="${@}"
_opt_short="fhl"
_opt_long="force,live,help,alterlive"
OPT=$(getopt -o ${_opt_short} -l ${_opt_long} -- "${@}")
if [[ ${?} != 0 ]]; then
    exit 1
fi

eval set -- "${OPT}"
unset OPT
unset _opt_short
unset _opt_long

while true; do
    case ${1} in
        -f | --force)
            force=true
            shift 1
            ;;
        -l | --live)
            checklive=true
            shift 1
            ;;
        -h | --help)
            _help
            shift 1
            exit 0
            ;;
        --alterlive)
            alterlive=true
            shift 1
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Invalid argument '${1}'" >&2
            _help
            exit 1
            ;;
    esac
done


if [[ "${checklive}" = true ]]; then
    if ! pacman -Qq alterlinux-calamares 1> /dev/null 2> /dev/null; then
        exit 0
    fi
fi


# ~/Desktopに相当するディレクトリを返します
get_desktop_dir() {
    local _user_config_dir _desktop_dir
    if [[ -v XDG_CONFIG_HOME ]]; then
        _user_config_dir="${XDG_CONFIG_HOME}"
    else
        _user_config_dir="${HOME}/.config"
    fi
    if [[ -f "${_user_config_dir}/user-dirs.dirs" ]]; then
        source "${_user_config_dir}/user-dirs.dirs"
    fi
    if [[ -v XDG_DESKTOP_DIR ]]; then
        _desktop_dir="${XDG_DESKTOP_DIR}"
    else
        _desktop_dir="${HOME}/Desktop"
    fi
    echo -n "${_desktop_dir}"
}

remove () {
    local _list
    local _file
    _list=($(echo "$@"))
    for _file in "${_list[@]}"; do
        if [[ -f ${_file} ]]; then
            rm -f "${_file}"
        elif [[ -d ${_file} ]]; then
            rm -rf "${_file}"
        fi
    done
}

#copy <コピー元> <コピー先>
copy() {
    if [[ ! -f "${1}" ]]; then
        echo "${1} was not found" >&2
        exit 1
    fi
    if [[ -f "${2}/$(basename "${1}")" ]] || [[ -f "${2}" ]] && [[ "${force}" = false ]]; then
        echo "File already exists" >&2
        exit 1
    fi

    cp "${1}" "${2}"
}

desktop_dir="$(get_desktop_dir)"

# calamaresのアイコン
source_file="/usr/share/alterlinux/desktop-file/calamares.desktop"
desktop_icon="${desktop_dir}/$(basename "${source_file}")"
copy "${source_file}" "${desktop_dir}"
os_name="$(
    if [[ -f "/etc/os-release" ]]; then
        source "/etc/os-release"
        echo -n "${NAME}"
    else
        echo -n "Alter Linux"
    fi
)"
sed -i "s/%OS_NAME%/${os_name}/g" "${desktop_icon}"


# welcome-page
source_file="/usr/share/alterlinux/desktop-file/welcome-to-alter.desktop"
desktop_icon="${desktop_dir}/$(basename "${source_file}")"
copy "${source_file}" "${desktop_dir}"


if [[ "${alterlive}" = true ]]; then
    remove "${HOME}/.config/autostart/genicon.desktop"
fi
